# Generated by Django 3.2.11 on 2022-02-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavTraineeSurgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
                ('trainee_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.traineesurgeon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nurse')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FavAnesthesiologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anesthesiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.anesthesiologist')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
