# Generated by Django 3.2.11 on 2022-02-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('hospital', '0002_auto_20220201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurgeryResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.resource')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
            ],
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('start_day', models.DateField()),
                ('end_day', models.DateField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('notes', models.TextField()),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgery')),
            ],
        ),
    ]
