# Generated by Django 4.0.1 on 2022-02-08 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surgery', '0001_initial'),
        ('user', '0001_initial'),
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTraineeSurgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgery')),
                ('trainee_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.traineesurgeon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedSurgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.resource')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nurse')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedAnesthesiologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('anesthesiologist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.anesthesiologist')),
                ('surgery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surgery.surgery')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
