# Generated by Django 3.2.11 on 2022-02-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('hospital', '0002_auto_20220201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedTraineeSurgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.DateField()),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.traineesurgeon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedSurgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.DateField()),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.DateField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.resource')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookedNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_minute', models.IntegerField()),
                ('end_minute', models.IntegerField()),
                ('start_hour', models.IntegerField()),
                ('end_hour', models.IntegerField()),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('day', models.DateField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.nurse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
