# Generated by Django 3.2.11 on 2022-02-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital', '0002_auto_20220201_1439'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('surgeon', 'Surgeon'), ('trainee_surgeon', 'Trainee Surgeon'), ('nurse', 'Nurse')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('surgeon', 'Surgeon'), ('trainee_surgeon', 'Trainee Surgeon'), ('nurse', 'Nurse')], max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=20)),
                ('experience', models.TextField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraineeSurgeon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('surgeon', 'Surgeon'), ('trainee_surgeon', 'Trainee Surgeon'), ('nurse', 'Nurse')], max_length=50)),
                ('registration_number', models.CharField(max_length=20)),
                ('experience', models.TextField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TraineeSurgeonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_day', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('trainee_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.traineesurgeon')),
            ],
        ),
        migrations.CreateModel(
            name='SurgeonSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('start_day', models.IntegerField()),
                ('end_day', models.IntegerField()),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
            ],
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('surgeon', 'Surgeon'), ('trainee_surgeon', 'Trainee Surgeon'), ('nurse', 'Nurse')], max_length=50)),
                ('registration_number', models.CharField(max_length=20)),
                ('is_sister', models.BooleanField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(default='dev', max_length=50)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Anesthesiologist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('surgeon', 'Surgeon'), ('trainee_surgeon', 'Trainee Surgeon'), ('nurse', 'Nurse')], max_length=50)),
                ('registration_number', models.CharField(max_length=20)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('surgeon', 'Surgeon'), ('trainee_surgeon', 'Trainee Surgeon'), ('nurse', 'Nurse')], max_length=50)),
                ('telephone', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
