# Generated by Django 4.0.1 on 2022-02-08 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('is_scl_content_creator', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('is_medical_staff', models.BooleanField(default=False, null=True)),
                ('is_admin_staff', models.BooleanField(default=False, null=True)),
                ('role', models.CharField(choices=[('admin-01', 'Administrator-01'), ('admin-02', 'Administrator-02'), ('admin-03', 'Administrator-03'), ('admin-04', 'Administrator-04'), ('admin-05', 'Administrator-05'), ('anesthesiologist', 'Anesthesiologist'), ('surgeon', 'Surgeon'), ('trainee_surgeon', 'Trainee Surgeon'), ('nurse', 'Nurse')], max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('surgeon', 'Surgeon'), ('trainee_surgeon', 'Trainee Surgeon'), ('nurse', 'Nurse')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('day', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'wednesday'), ('thur', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userprofile')),
                ('level', models.IntegerField()),
            ],
            bases=('user.userprofile',),
        ),
        migrations.CreateModel(
            name='Anesthesiologist',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userprofile')),
                ('registration_number', models.CharField(max_length=20)),
            ],
            bases=('user.userprofile',),
        ),
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userprofile')),
                ('role', models.CharField(default='dev', max_length=50)),
            ],
            bases=('user.userprofile',),
        ),
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userprofile')),
                ('registration_number', models.CharField(max_length=20)),
                ('is_sister', models.BooleanField()),
            ],
            bases=('user.userprofile',),
        ),
        migrations.CreateModel(
            name='Surgeon',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userprofile')),
                ('specialty', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=20)),
            ],
            bases=('user.userprofile',),
        ),
        migrations.CreateModel(
            name='TraineeSurgeon',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userprofile')),
                ('specialty', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=20)),
            ],
            bases=('user.userprofile',),
        ),
        migrations.CreateModel(
            name='TraineeSurgeonSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.session')),
                ('trainee_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.traineesurgeon')),
            ],
            bases=('user.session',),
        ),
        migrations.CreateModel(
            name='SurgeonSession',
            fields=[
                ('session_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.session')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.surgeon')),
            ],
            bases=('user.session',),
        ),
    ]
