# Generated by Django 3.2.11 on 2022-02-01 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='resource',
            name='unit',
            field=models.CharField(choices=[('ml', 'Milliliters'), ('mg', 'Milligrams'), ('pcs', 'Pieces')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='surgeryclick',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgeryclick',
            name='resource_type',
            field=models.CharField(choices=[('drug', 'Drug'), ('equipment', 'Equipment')], default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theater',
            name='hospital',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospital',
            name='telephone',
            field=models.CharField(max_length=10),
        ),
    ]
